-- NexusPlay Retry UI Flow Inspector v1
-- TESTING ONLY: observes the normal post-raid Retry UI/input flow.
-- Does not invoke remotes, click buttons, or bypass server validation.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local UserInputService = game:GetService("UserInputService")
local LocalPlayer = Players.LocalPlayer

local NetworkComm = ReplicatedStorage:WaitForChild("NetworkComm")
local RaidsService = NetworkComm:WaitForChild("RaidsService")
local BossIslandService = NetworkComm:WaitForChild("BossIslandService")

local active = true
local raidEnded = false
local postEndUntil = 0
local conns = {}
local watched = {}
local log = {}

local function emit(msg)
    local line = os.date("%H:%M:%S") .. " | " .. tostring(msg)
    print("[Retry UI Flow Inspector v1] " .. line)
    table.insert(log, line)
    if #log > 250 then table.remove(log, 1) end
end

local function safeText(obj)
    local t = ""
    pcall(function() t = obj.Text end)
    return tostring(t or "")
end

local function visible(obj)
    local v = false
    pcall(function() v = obj.Visible end)
    return v
end

local function interesting(obj)
    if not obj:IsA("GuiObject") then return false end

    local n = string.lower(obj.Name)
    local t = string.lower(safeText(obj))

    return n:find("retry", 1, true)
        or n:find("again", 1, true)
        or n:find("continue", 1, true)
        or n:find("claim", 1, true)
        or n:find("next", 1, true)
        or t:find("retry", 1, true)
        or t:find("again", 1, true)
        or t:find("continue", 1, true)
        or t:find("claim", 1, true)
        or t:find("next", 1, true)
end

local function describe(obj, prefix)
    if not obj or not obj.Parent then return end

    local pos, size = "?", "?"
    pcall(function()
        pos = tostring(obj.AbsolutePosition)
        size = tostring(obj.AbsoluteSize)
    end)

    emit(
        prefix
        .. " | " .. obj:GetFullName()
        .. " | Class=" .. obj.ClassName
        .. " | Text=" .. safeText(obj)
        .. " | Visible=" .. tostring(visible(obj))
        .. " | Pos=" .. pos
        .. " | Size=" .. size
    )
end

local function watch(obj)
    if not active or not interesting(obj) or watched[obj] then return end
    watched[obj] = true

    describe(obj, "UI CANDIDATE")

    if obj:IsA("GuiButton") then
        local ok, c = pcall(function()
            return obj.Activated:Connect(function()
                emit("BUTTON ACTIVATED | " .. obj:GetFullName())
                emit("BUTTON INFO | Text=" .. safeText(obj))
                emit("FLOW | normal UI activation observed; no action was generated by inspector")
            end)
        end)
        if ok and c then table.insert(conns, c) end
    end

    local ok1, c1 = pcall(function()
        return obj:GetPropertyChangedSignal("Visible"):Connect(function()
            describe(obj, "UI VISIBLE CHANGED")
        end)
    end)
    if ok1 and c1 then table.insert(conns, c1) end

    local ok2, c2 = pcall(function()
        return obj:GetPropertyChangedSignal("Text"):Connect(function()
            describe(obj, "UI TEXT CHANGED")
        end)
    end)
    if ok2 and c2 then table.insert(conns, c2) end
end

local function scanGui()
    local pg = LocalPlayer:WaitForChild("PlayerGui")

    for _, obj in ipairs(pg:GetDescendants()) do
        watch(obj)
    end

    table.insert(conns, pg.DescendantAdded:Connect(function(obj)
        watch(obj)
        if raidEnded and interesting(obj) then
            describe(obj, "POST-END UI ADDED")
        end
    end))

    emit("GUI WATCH | PlayerGui descendants + dynamic additions")
end

local function serialize(v, depth, seen)
    depth = depth or 0
    seen = seen or {}

    if depth > 3 then return "<depth>" end

    local tv = typeof(v)
    if tv ~= "table" then
        if tv == "Instance" then
            return "<Instance:" .. v:GetFullName() .. ">"
        end
        return tostring(v)
    end

    if seen[v] then return "<cycle>" end
    seen[v] = true

    local out = {}
    for k, x in pairs(v) do
        out[tostring(k)] = serialize(x, depth + 1, seen)
    end
    return out
end

local function attachRemote(remote)
    if not remote:IsA("RemoteEvent") then return end

    local name = remote.Name

    local ok, conn = pcall(function()
        return remote.OnClientEvent:Connect(function(...)
            local args = table.pack(...)

            if name == "RaidEnded_Signal" then
                raidEnded = true
                postEndUntil = os.clock() + 15
                emit("RAID END | success=" .. tostring(args[1]))
                emit("POST-END WINDOW | 15 seconds; watch UI + input")
                return
            end

            if name == "RaidDataUpdated_Signal" then
                local d = args[1]
                if type(d) == "table" then
                    emit(
                        "RAID DATA"
                        .. " | RaidID=" .. tostring(d.RaidID or d.BossID)
                        .. " | Players=" .. tostring(type(d.Players) == "table" and #d.Players or 0)
                        .. " | RetryTime=" .. tostring(d.RetryTime)
                        .. " | RetryingPlayers=" .. tostring(d.RetryingPlayers)
                    )
                end
            elseif name == "LobbyRemoved_Signal" then
                emit("LOBBY REMOVED | " .. tostring(serialize(args[1])))
            elseif name == "MatchStateUpdated_Signal" then
                emit("MATCH STATE | " .. tostring(args[1]))
            end
        end)
    end)

    if ok and conn then table.insert(conns, conn) end
end

local function attachChildren(container)
    for _, obj in ipairs(container:GetChildren()) do
        attachRemote(obj)
    end
    table.insert(conns, container.ChildAdded:Connect(attachRemote))
end

attachChildren(RaidsService)
attachChildren(BossIslandService)

local okInput, inputConn = pcall(function()
    return UserInputService.InputBegan:Connect(function(input, gameProcessed)
        if not raidEnded or os.clock() > postEndUntil then return end

        local kind = input.UserInputType
        if kind ~= Enum.UserInputType.MouseButton1
            and kind ~= Enum.UserInputType.Touch then
            return
        end

        local pos = input.Position
        emit(
            "POST-END INPUT | type=" .. tostring(kind)
            .. " | pos=" .. tostring(pos)
            .. " | gameProcessed=" .. tostring(gameProcessed)
        )

        local pg = LocalPlayer:FindFirstChildOfClass("PlayerGui")
        if not pg then return end

        local ok, objs = pcall(function()
            return pg:GetGuiObjectsAtPosition(pos.X, pos.Y)
        end)

        if ok and type(objs) == "table" then
            for i, obj in ipairs(objs) do
                if i > 12 then break end
                describe(obj, "HIT-TEST GUI")
            end
        else
            emit("HIT-TEST | unavailable")
        end
    end)
end)

if okInput and inputConn then table.insert(conns, inputConn) end

scanGui()

emit("STARTED | Retry UI Flow Inspector v1")
emit("IMPORTANT | Run one raid normally")
emit("IMPORTANT | After RaidEnded, press the game's normal Retry button manually")
emit("IMPORTANT | Inspector never clicks, fires, invokes, or alters anything")
